name: Build docker image and deploy to docker hub
on:
  push:
    branchs:
      - main
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN:  ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup up Docker build
      uses: docker/setup-buildx-action@v1
    - name: login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push image
      uses: docker/buils-push-action@v2
      with:
        context: ./
        push: true
        dockerfile: ./Dockerfile
        tags: vazidcovlant/nomaddemo:latest