name: Build docker image and deploy to docker hub
on:
  push:
    branches:
      - main
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN:  ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set permission for private key
      run: |  
        echo "${{ secrets.AWS_PRIVATE_KEY }}" | tr -d '\r' > server-key.pem
        chmod 600 server-key.pem
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Clean up Docker system
      run: |
        ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-3-85-91-213.compute-1.amazonaws.com << 'EOF'
          sudo docker system prune -af
        EOF
# running nomad pack
    - name: Run nomad pack
      run: |
        ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-3-85-91-213.compute-1.amazonaws.com << 'EOF'
          cd ~/my_nomad_packs/packs/hello_pack
          export NOMAD_TOKEN=$(cat nomad_token.txt)
          nomad-pack info .
          nomad-pack render .
          nomad-pack run .
          nomad-pack list
        EOF
    

    