name: Build docker image and deploy to docker hub
on:
  push:
    branches:
      - main
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN:  ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set permission for private key
      run: |  
        echo "${{ secrets.AWS_PRIVATE_KEY }}" | tr -d '\r' > server-key.pem
        chmod 600 server-key.pem
    - name: Copy files
      run: |
        scp -o StrictHostKeyChecking=no -i server-key.pem nomad.hcl ubuntu@ec2-3-85-91-213.compute-1.amazonaws.com:~/nomad.hcl
        scp -o StrictHostKeyChecking=no -i server-key.pem httpd.nomad.hcl ubuntu@ec2-3-85-91-213.compute-1.amazonaws.com:~/httpd.nomad.hcl
        scp -o StrictHostKeyChecking=no -i server-key.pem website.nomad.hcl ubuntu@ec2-3-85-91-213.compute-1.amazonaws.com:~/website.nomad.hcl
        scp -r -o StrictHostKeyChecking=no -i server-key.pem my_nomad_packs ubuntu@ec2-3-85-91-213.compute-1.amazonaws.com:~/
    - name: Check nomad installed
      run: |
        ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-3-85-91-213.compute-1.amazonaws.com << 'EOF'
          if ! command -v nomad &> /dev/null
          then
            echo "Installing nomad dev cluster..."
            sudo apt update
            wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt update && sudo apt install -y nomad
          else
            echo "Nomad is already installed"
          fi
        EOF
    - name: running nomad cluster
      run: |
        ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-3-85-91-213.compute-1.amazonaws.com << 'EOF'
          echo "Running nomad in dev mode"
          nohup nomad agent -dev --config=$HOME/nomad.hcl > nomad.log 2>&1 &
        EOF
    - name: Ensure Docker is installed
      run: |
        ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-3-85-91-213.compute-1.amazonaws.com << 'EOF'
          if ! command -v docker &> /dev/null
          then
            echo "Installing Docker..."
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo usermod -aG docker ubuntu
            newgrp docker
          else
            echo "Docker is already installed."
          fi
        EOF
    - name: Clean up Docker system
      run: |
        ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-3-85-91-213.compute-1.amazonaws.com << 'EOF'
          sudo docker system prune -af
        EOF
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Running nomad job
      run: |
        ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-3-85-91-213.compute-1.amazonaws.com << 'EOF'
          nomad job run ~/httpd.nomad.hcl
          nomad job run ~/website.nomad.hcl
        EOF
    - name: Install nomad pack
      run: |
        ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-3-85-91-213.compute-1.amazonaws.com << 'EOF'
        if ! command nomad-pack &> /dev/null
        then 
          echo "Installing nomad pack..."
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install -y nomad-pack
        else
          echo "Nomad-pack already installed"
        fi
        EOF
    - name: Run nomad pack
      run: |
        ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-3-85-91-213.compute-1.amazonaws.com << 'EOF'
          cd ~/my_nomad_packs/packs/hello_pack
          nomad-pack info .
          nomad-pack render .
          nomad-pack run .
          nomad-pack list
        EOF